###### INPUTS ######
input PackageOpts {
  name: String
  manager: String
  limit: Int
  page: Int
}

input ToolchainOpts {
  name: String
  limit: Int
  page: Int
}


###### TYPES ######
"""
Image is returned by the image query.
It contains information about an image.
"""
type Image {
  id: String!
  ami: String!
  distros: [Distro!]!
  kernel: String!
  lastDeployed: Time!
  latestTask: Task
  name: String!
  packages(opts: PackageOpts!): PackagesResponse!
  toolchains(opts: ToolchainOpts!): [Toolchain!]!
  versionId: String!
}

"""
PackagesResponse is the return value for the packages query.
It contains an array of Packages matching the filter conditions and count information.
"""
type PackagesResponse {
  filteredPackagesCount: Int
  packages: [Package!]!
  totalPackagesCount: Int!
}

type Package {
  name: String!
  manager: String!
  version: String!
}

"""
ToolchainsResponse is the return value for the toolchains query.
It contains an array of Toolchains matching the filter conditions and count information.
"""
type ToolchainsResponse {
  filteredToolchainsCount: Int
  toolchains: [Toolchain!]!
  totalToolchainsCount: Int!
}

type Toolchain {
  name: String!
  path: String!
  version: String!
}


